version: "3.9"
services:
  app:
    image: coupons
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      DATABASE_DSN: "local:local1234@tcp(db:3306)/coupons"
    ports:
      - "2345:2345"
      - "50051:50051"
      - "8000:8000"
    links:
      - db
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'coupons'
      MYSQL_USER: 'local'
      MYSQL_PASSWORD: 'local1234'
      MYSQL_ROOT_PASSWORD: 'local1234'
    ports:
      - '3307:3306'
    expose:
      - '3306'
    volumes:
      - './.mysql-data/db:/var/lib/mysql'